#!/usr/bin/env python3
"""Formal-submission cleanup of journal_manuscript_v2.tex and
companion_categorical.tex.

Defect classes fixed (user directives 1-4):
1. Internal artifact references in captions ("Artifact: ... .png/.json").
2. Changelog/diary-style references to earlier versions, predecessor
   drafts, defect-repair codes, strawman/phantom points, chat-history
   experiment codes (E-V5, M4b, V8, Route 5, RC6, BT1, D-N1...).
3. Figure filenames removed from captions; source-data linkage now
   carried by the Data Availability statement.
4. AI names outside the declaration (deepseek_bridge paths in text).

Whitespace-flexible matching: patterns are tokenized on whitespace and
joined with \\s+, so hard line wraps in the .tex do not matter.
Every replacement asserts its expected match count.
"""
import re
import sys

MAIN = "/home/z/my-project/scripts/journal_manuscript_v2.tex"
COMP = "/home/z/my-project/scripts/companion_categorical.tex"

FLEX = re.compile(r"\s+")
REPORT = []


def flexpat(s):
    toks = FLEX.split(s.strip())
    return r"\s+".join(re.escape(t) for t in toks)


def apply(text, old, new, count, tag):
    pat = re.compile(flexpat(old))
    hits = pat.findall(text)
    if len(hits) != count:
        REPORT.append(f"MISS [{tag}] expected {count} got {len(hits)}: {old[:70]!r}")
        return text, False
    text = pat.sub(lambda m: new, text)
    REPORT.append(f"OK   [{tag}] x{count}")
    return text, True


def regex(text, pat, new, count, tag, flags=0):
    pat = re.compile(pat, flags)
    hits = pat.findall(text)
    if len(hits) != count:
        REPORT.append(f"MISS [{tag}] expected {count} got {len(hits)}")
        return text, False
    text = pat.sub(lambda m: new, text)
    REPORT.append(f"OK   [{tag}] x{count}")
    return text, True


def main():
    ok_all = True
    src = open(MAIN, encoding="utf-8").read()

    # ---------------- header comment block ----------------
    src, ok = regex(
        src,
        r"% =====================================================================\n"
        r"%  journal_manuscript_v2.*?\n(?=\\documentclass)",
        "% =====================================================================\n"
        "%  journal_manuscript_v2.tex -- main manuscript\n"
        "%  Target journal: Bulletin of Mathematical Biology (Springer).\n"
        "%  Author-year citations (natbib); reference list in\n"
        "%  journal_manuscript_v2_bmb_refs.tex (generated by\n"
        "%  scripts/build_bmb_refs.py). Figures resolve from the current\n"
        "%  directory and from ../download/ via \\graphicspath. The\n"
        "%  categorical framework is carried by the standalone theory\n"
        "%  companion (scripts/companion_categorical.tex), cross-cited\n"
        "%  here; the categorical subsection states it in adapted form\n"
        "%  only.\n",
        1, "header", re.S)
    ok_all &= ok

    # ---------------- abstract ----------------
    src, ok = apply(src,
        "We prove a refinement--resolution bridge (Theorem~B$'$): under mesh",
        "We prove a refinement--resolution bridge: under mesh", 1, "abs-B")
    ok_all &= ok
    src, ok = apply(src,
        "the dual-cell reconstruction converges strongly in $L^1$, and the "
        "total-variation claims of earlier formulations are replaced by an "
        "exact counterexample calculus;",
        "the dual-cell reconstruction converges strongly in $L^1$, and an "
        "exact counterexample calculus shows that total-variation "
        "convergence fails in general;", 1, "abs-tv")
    ok_all &= ok
    src, ok = apply(src,
        "tie-break-robust across four alternative selection rules, E-V8; "
        "the underlying event measures stabilize at the "
        "Glivenko--Cantelli rate across random panels, E-E32), while the",
        "tie-break-robust across four alternative selection rules, and the "
        "underlying event measures stabilize at the "
        "Glivenko--Cantelli rate across random panels), while the", 1, "abs-codes")
    ok_all &= ok

    # ---------------- introduction ----------------
    for tag, old, new in [
        ("i-R1", r"\item \textbf{[R1]} the atom structure", r"\item the atom structure"),
        ("i-R2", r"\item \textbf{[R2]} the two-layer separation", r"\item the two-layer separation"),
        ("i-R3", r"\item \textbf{[R3]} the regime dichotomy", r"\item the regime dichotomy"),
        ("i-R4", r"\item \textbf{[R4]} the value function", r"\item the value function"),
        ("i-E", r"\item \textbf{[E-series]} the measure-derived metric", r"\item the measure-derived metric"),
    ]:
        src, ok = apply(src, old, new, 1, tag)
        ok_all &= ok
    src, ok = apply(src,
        "(Theorem~B$'$, \\S\\ref{sec:theoremB}), with the "
        "exact counterexample calculus that separates what is provable from "
        "what is false in earlier formulations;",
        "(Theorem~\\ref{thm:Bprime}, \\S\\ref{sec:theoremB}), with an "
        "exact counterexample calculus delimiting what is provable (weak "
        "convergence, strong cell-wise reconstruction) from what fails "
        "(total-variation convergence);", 1, "i-R1-tv")
    ok_all &= ok
    src, ok = apply(src,
        "with matched responses ($r = +0.32$, $+0.22$; E-V7), is robust "
        "to the tie-break convention (E-V8: $r \\in [+0.386, +0.396]$",
        "with matched responses ($r = +0.32$, $+0.22$; \\S\\ref{sec:v7}), is "
        "robust to the tie-break convention (\\S\\ref{sec:v8}: "
        "$r \\in [+0.386, +0.396]$", 1, "i-codes")
    ok_all &= ok
    src, ok = apply(src,
        "the Glivenko--Cantelli rate across random panels (E-E32).",
        "the Glivenko--Cantelli rate across random panels (\\S\\ref{sec:e32}).",
        1, "i-e32")
    ok_all &= ok

    # ---------------- notation section removal ----------------
    src, ok = regex(
        src,
        r"% =====================================================================\n"
        r"\\section\{Notation protocol and the R/D/E hierarchy\}"
        r"\\label\{sec:notation\}.*?\\end\{itemize\}\n\n",
        "", 1, "notation-del", re.S)
    ok_all &= ok

    # ---------------- section / subsection titles ----------------
    for tag, old, new, cnt in [
        ("t-D1", r"\subsection{[D1] The measure}", r"\subsection{The atomic curvature measure}", 1),
        ("t-D2", r"\subsection{[D2] The measure-theoretic sensitivity metric}",
         r"\subsection{The measure-theoretic sensitivity metric}", 1),
        ("t-D3", r"\subsection{[D3] The value-function layer (Alexandrov)}",
         r"\subsection{The value-function layer (Alexandrov)}", 1),
        ("t-D4", r"\subsection{[D4] The value--flux coupling}",
         r"\subsection{The value--flux coupling}", 1),
        ("t-D5", r"\subsection{[D5] The categorical reading, in brief}\label{sec:categorical}",
         r"\subsection{The categorical reading, in brief}\label{sec:categorical}", 1),
        ("t-Rport", r"\subsection{[R-port] Bridge to parametric FBA}",
         r"\subsection{Bridge to parametric FBA}", 1),
        ("t-M1", r"\subsection{[E-M1] Active-set curvature verification}",
         r"\subsection{Active-set curvature verification}\n\\label{sec:m1}", 1),
        ("t-M3", r"\subsection{[E-M3] Double-knockout epistasis and path dependence}",
         r"\subsection{Double-knockout epistasis and path dependence}", 1),
        ("t-M4", r"\subsection{[E-M4] Regime dial}",
         r"\subsection{Regime dial}", 1),
        ("t-V1", r"\subsection{[E-V1] The value function as canonical carrier}",
         r"\subsection{The value function as canonical carrier}\n\\label{sec:v1}", 1),
        ("t-E22", r"\subsection{[E-E22] The gene panel and GPR classes}",
         r"\subsection{The gene panel and GPR classes}\n\\label{sec:e22}", 1),
        ("t-E23", r"\subsection{[E-E23] Multi-condition support}",
         r"\subsection{Multi-condition support}\n\\label{sec:e23}", 1),
        ("t-V5", r"\subsection{[E-V5] Transcriptional response under carbon depletion}",
         r"\subsection{Transcriptional response under carbon depletion}\n\\label{sec:v5}", 1),
        ("t-V6", r"\subsection{[E-V6] The layer decision}",
         r"\subsection{The layer decision}\n\\label{sec:v6}", 1),
        ("t-V7", r"\subsection{[E-V7] Path robustness: what survives a trajectory change}",
         r"\subsection{Path robustness: what survives a trajectory change}\n\\label{sec:v7}", 1),
        ("t-V8", r"\subsection{[E-V8] Tie-break robustness: the association as a property",
         r"\subsection{Tie-break robustness: the association as a property", 1),
        ("t-E32", r"\subsection{[E-E32] Event-measure stabilization",
         r"\subsection{Event-measure stabilization", 1),
        ("t-E25", r"\subsection{[E-E25] Platform-by-class disambiguation ($2 \times 2$)}",
         r"\subsection{Platform-by-class disambiguation ($2 \times 2$)}\n\\label{sec:e25}", 1),
        ("t-E26", r"\subsection{[E-E26] Protein abundance versus protein change}",
         r"\subsection{Protein abundance versus protein change}\n\\label{sec:e26}", 1),
        ("t-E27", r"\subsection{[E-E27] Protein-layer null}",
         r"\subsection{Protein-layer null}\n\\label{sec:e27}", 1),
        ("t-Bp", r"\section{The refinement--resolution bridge (Theorem B$'$)}",
         r"\section{The refinement--resolution bridge}", 1),
        ("t-counts", r"\section{The counts ledger}\label{sec:counts}",
         r"\section{Disambiguation of near-colliding counts}\label{sec:counts}", 1),
    ]:
        src, ok = apply(src, old, new, cnt, tag)
        ok_all &= ok

    # ============ STAGE 2: in-text experiment-code references ============
    S2 = [
        # rem:lock tail
        (r"$\rho(\kmu, \kk^{\mathrm{lex}}) = 0.99998$ (E-V5), the trajectory "
         r"substitutions of E-V7 reproduce the association under the same "
         r"declared selection on two further paths, and E-V8 holds the",
         r"$\rho(\kmu, \kk^{\mathrm{lex}}) = 0.99998$ (\S\ref{sec:v5}), the "
         r"trajectory substitutions of \S\ref{sec:v7} reproduce the "
         r"association under the same declared selection on two further "
         r"paths, and \S\ref{sec:v8} holds the", 1),
        (r"(R2 remarks in \S\ref{sec:theoremB}); its resolution",
         r"(see \S\ref{sec:theoremB}); its resolution", 1),
        (r"The Kantorovich--Rubinstein (flat) norm used in Theorem~B$'$ is",
         r"The Kantorovich--Rubinstein (flat) norm used in the "
         r"refinement--resolution bridge is", 1),
        (r"Theorem~B$'$(iv). Its per-reaction masses",
         r"Theorem~\ref{thm:Bprime}(iv). Its per-reaction masses", 1),
        (r"interpolation; Theorem~B$'$ governs",
         r"interpolation; Theorem~\ref{thm:Bprime} governs", 1),
        # D3/D4 region
        (r"second-difference mass moves by ten orders of magnitude (E-M1, "
         r"\S\ref{sec:computational}).",
         r"second-difference mass moves by ten orders of magnitude "
         r"(\S\ref{sec:m1}).", 1),
        (r"the evidence (E-V5, E-V6) actually lives.",
         r"the evidence (\S\ref{sec:v5}, \S\ref{sec:v6}) actually lives.", 1),
        (r"path segment residuals $\le 8 \times 10^{-14}$ (E-M1); $\Phi$ "
         r"piecewise affine at $4.2 \times 10^{-13}$ (E-V1).",
         r"path segment residuals $\le 8 \times 10^{-14}$ (\S\ref{sec:m1}); "
         r"$\Phi$ piecewise affine at $4.2 \times 10^{-13}$ "
         r"(\S\ref{sec:v1}).", 1),
        # sec-law consequences / dichotomy
        (r"of a \emph{fixed} complex (as measured in the $M4b$ census) are",
         r"of a \emph{fixed} complex (as measured in the regime-dial "
         r"census, \S\ref{sec:m4}) are", 1),
        (r"\begin{proposition}[Regime dichotomy; M4a in closed form]",
         r"\begin{proposition}[Regime dichotomy, in closed form]", 1),
        (r"Measured slopes on the $M4a$ design: $2.000$ (smooth) and $1.00$",
         r"Measured slopes on the regime-dial design (\S\ref{sec:m4}): "
         r"$2.000$ (smooth) and $1.00$", 1),
        (r"(the measured regime dial, \S\ref{sec:m4}).",
         r"(measured in \S\ref{sec:m4}).", 1),
        (r"(mask-type events --- rerouting without growth loss, the "
         r"RC6/Kochanowski pattern). On the iML1515 cut: $12$ flux events "
         r"vs $1$ value atom, $11$ objective-invisible; on the E24 "
         r"trajectory (E-V6) the",
         r"(mask-type events --- rerouting without growth loss, the "
         r"Kochanowski pattern \citep{kochanowski2013}). On the iML1515 "
         r"cut: $12$ flux events vs $1$ value atom, $11$ "
         r"objective-invisible; on the reference trajectory "
         r"(\S\ref{sec:v6}) the", 1),
        # computational validation
        (r"The $M4a$ scaling slope is $1.00$ on the interacting stratum; "
         r"the $M4b$ census resolves the thin-wedge sliver structure",
         r"The scaling slope is $1.00$ on the interacting stratum; the "
         r"regime-dial census resolves the thin-wedge sliver structure", 1),
        (r"Reaction-based sampling on the E22 physiology (iJO1366): $438$ of",
         r"Reaction-based sampling on the reference physiology (glucose "
         r"$5.0 \to 1.0$, oxygen $22 \to 5$; iJO1366): $438$ of", 1),
        (r"the panel shares exactly one b-number with the precursor "
         r"MAPPED-15 ($b2097$)",
         r"the panel shares exactly one b-number with the precursor panel "
         r"($b2097$)", 1),
        (r"the discrepancy that motivated the recalibration to $\kmu$ "
         r"(E-V5).",
         r"the discrepancy that motivated the recalibration to $\kmu$ "
         r"(\S\ref{sec:v5}).", 1),
        (r"The endogeneity audit is clean",
         r"The endogeneity check is clean", 1),
        (r"On the deterministic lexicographic trajectory (E22 physiology, "
         r"iJO1366),",
         r"On the deterministic lexicographic trajectory (the reference "
         r"physiology, iJO1366),", 1),
        (r"The dissociation previously established with the precursor "
         r"$\kk$ predictor is metric-robust:",
         r"The dissociation observed with the precursor $\kk$ predictor is "
         r"metric-robust:", 1),
        (r"the platform-matched design, reported as an honest negative.",
         r"the platform-matched design, reported as a negative result.", 1),
        (r"All value-layer attribution arms, on the frozen V5 protocol "
         r"(iJO1366, E22 physiology, $n = 424$):",
         r"All value-layer attribution arms, under the locked protocol of "
         r"\S\ref{sec:v5} (iJO1366, the reference physiology, $n = 424$):", 1),
        (r"Three trajectories through the same LP (frozen engine, seed, "
         r"panel, statistics; only the path and its matched response vary; "
         r"Fig~\ref{fig:v7}): P0 glucose decline (E22 anchors; the V6 "
         r"control), P1 oxygen limitation",
         r"Three trajectories through the same LP (same engine, seed, "
         r"panel, statistics; only the path and its matched response vary; "
         r"Fig~\ref{fig:v7}): P0 glucose decline (reference-physiology "
         r"anchors; the layer-decision control of \S\ref{sec:v6}), P1 "
         r"oxygen limitation", 1),
        (r"chamber crossings (V6 reproduced digit-exactly), while P1 has",
         r"chamber crossings (the \S\ref{sec:v6} control, reproduced "
         r"digit-exactly), while P1 has", 1),
        (r"The E24 single-chamber structure is a property of the "
         r"glucose-decline design, not a law.",
         r"The single-chamber structure of the reference trajectory is a "
         r"property of the glucose-decline design, not a law.", 1),
        (r"and the P1/P2 predictors correlate with the E24 carbon response "
         r"at $r = +0.378$ / $+0.391$ --- the per-gene",
         r"and the P1/P2 predictors correlate with the primary-panel carbon "
         r"response at $r = +0.378$ / $+0.391$ --- the per-gene", 1),
        (r"member of a family. V8 freezes the entire V5/V6 protocol "
         r"(iJO1366, E22 physiology anchors, $8\times$ refinement, the "
         r"$433$-gene E24 panel, the M3D carbon-depletion response, the "
         r"reference-level confound control) and varies",
         r"member of a family. The tie-break experiment fixes the entire "
         r"protocol of the primary association (iJO1366, "
         r"reference-physiology anchors, $8\times$ refinement, the "
         r"$433$-gene panel, the M3D carbon-depletion response, the "
         r"reference-level confound control) and varies", 1),
        (r"the locked metric (control: reproduces V5 digit-exactly, "
         r"$r = +0.3954$);",
         r"the locked metric (control: reproduces the primary association "
         r"digit-exactly, $r = +0.3954$);", 1),
        (r"this closes the robustness ledger: the",
         r"this completes the robustness picture: the", 1),
        # E32 section
        (r"has a near-term statistical form, proposed as E32 and executed "
         r"here on three existing data sources: random straight cuts "
         r"through the M4b $(q_{\mathrm{glc}}, q_{O_2})$ signature plane",
         r"has a near-term statistical form, executed here on three data "
         r"sources: random straight cuts through the "
         r"$(q_{\mathrm{glc}}, q_{O_2})$ signature plane", 1),
        (r"the thirteen M1 parameter sweeps ($2$ affine, $11$ "
         r"event-bearing), and the E24 protocol of this paper (gene panel "
         r"and trajectory).",
         r"the thirteen parameter sweeps of \S\ref{sec:m1} ($2$ affine, "
         r"$11$ event-bearing), and the panel protocol of this paper (gene "
         r"panel and trajectory).", 1),
        (r"Sweep panels (thirteen M1 families) stabilize",
         r"Sweep panels (the thirteen sweep families) stabilize", 1),
        (r"The E24 gene panel: the $\kappa$ distribution stabilizes",
         r"The gene panel: the $\kappa$ distribution stabilizes", 1),
        (r"The E24 trajectory event point measure is a \emph{four-atom} "
         r"object: the four design corners of the physiology anchors carry "
         r"the entire flux-layer mass ($288.77$; the V5 mass to the digit) "
         r"--- the one-chamber structure of E-V6 in its event form.",
         r"The trajectory event point measure is a \emph{four-atom} object: "
         r"the four design corners of the physiology anchors carry the "
         r"entire flux-layer mass ($288.77$, the primary association's "
         r"flux-layer mass to the digit) --- the one-chamber structure of "
         r"\S\ref{sec:v6} in its event form.", 1),
        (r"Interpretation: the mean-field instinct is confirmed",
         r"Interpretation: the mean-field intuition is confirmed", 1),
        (r"question (Route 5 proper: model-family sequences) remains open.",
         r"question (refinement along explicit model-family sequences) "
         r"remains open.", 1),
        (r"remains open. Artifact: \texttt{deepseek\_bridge/} "
         r"\texttt{e32\_event\_measure\_stabilization.}\{\texttt{json,"
         r"csv,png}\}.",
         r"remains open.", 1),
    ]
    for i, (old, new, cnt) in enumerate(S2):
        src, ok = apply(src, old, new, cnt, f"S2-{i}")
        ok_all &= ok

    # ============ STAGE 3: captions and artifact lines ============
    S3 = [
        (r"all sweeps are cold-started and deterministic. Artifact: "
         r"\texttt{m1\_m3/fig\_m1\_summary.png} / \texttt{m1\_summary.json}.}",
         r"all sweeps are cold-started and deterministic.}", 1),
        (r"[Theorem~\ref{thm:coupling}] Machine verification of the "
         r"value--flux crease coupling. The controlled follower-variable "
         r"LPs:",
         r"Machine verification of the value--flux crease coupling "
         r"(Theorem~\ref{thm:coupling}). The controlled follower-variable "
         r"LPs:", 1),
        (r"events and all $4$ clusters. Artifact: "
         r"\texttt{alexandrov\_bridge/coupling\_figures.png} / "
         r"\texttt{coupling\_results.json}.}",
         r"events and all $4$ clusters.}", 1),
        (r"[E-V8] Tie-break robustness of the association (V5 protocol "
         r"frozen; only the stage-3 selection rule varies).",
         r"Tie-break robustness of the association (primary protocol "
         r"fixed; only the stage-3 selection rule varies).", 1),
        (r"the tie-break-freeness of Proposition~\ref{prop:alex}. Artifact: "
         r"\texttt{deepseek\_bridge/v8\_tiebreak\_robustness.}"
         r"\{\texttt{json, csv,png}\}.}",
         r"the tie-break-freeness of Proposition~\ref{prop:alex}.}", 1),
        (r"[E-V5] The primary association. (a) Per-gene",
         r"The primary association. (a) Per-gene", 1),
        (r"$\kk$ (E22, plain-FBA), the engine control",
         r"$\kk$ (reference physiology, plain-FBA), the engine control", 1),
        (r"agreement between $\kmu$ and the E22 $\kk$.",
         r"agreement between $\kmu$ and the plain-FBA $\kk$.", 1),
        (r"agreement between $\kmu$ and the plain-FBA $\kk$. Artifact: "
         r"\texttt{deepseek\_bridge/v5\_e24\_recalibration.png} / "
         r"\texttt{v5\_e24\_recalibration.json}.}",
         r"agreement between $\kmu$ and the plain-FBA $\kk$.}", 1),
        (r"[E-V7] Path robustness. Three trajectories through the same",
         r"Path robustness. Three trajectories through the same", 1),
        (r"the P1/P2 predictors correlate with the E24 carbon response at "
         r"$r = +0.378$/$+0.391$. Artifact: "
         r"\texttt{deepseek\_bridge/v7\_path\_robustness.png} / "
         r"\texttt{v7\_path\_robustness.json}.}",
         r"the P1/P2 predictors correlate with the primary-panel carbon "
         r"response at $r = +0.378$/$+0.391$.}", 1),
        (r"[E-V8] Tie-break robustness. (a) The association across the",
         r"Tie-break robustness. (a) The association across the", 1),
        (r"the tie-break binds (of 57). The value layer is invariant to "
         r"$0.0$ across all variants. Artifact: "
         r"\texttt{deepseek\_bridge/v8\_tiebreak\_robustness.png} / "
         r"\texttt{v8\_tiebreak\_robustness.json}.}",
         r"the tie-break binds (of 57). The value layer is invariant to "
         r"$0.0$ across all variants.}", 1),
        (r"[E-E32] Event-measure stabilization. (a) M4b random cuts:",
         r"Event-measure stabilization. (a) Random-cut panels:", 1),
        (r"(b) M1 sweep panels: stabilization with a",
         r"(b) Parameter-sweep panels: stabilization with a", 1),
        (r"(c) E24 gene panel: the $\kappa$",
         r"(c) Gene panel: the $\kappa$", 1),
        (r"(d) E24 trajectory: the $L^1$-reconstruction regime",
         r"(d) Reference trajectory: the $L^1$-reconstruction regime", 1),
        (r"exact ($d_{BL} \equiv 0$) from $m \ge 8$. Artifact: "
         r"\texttt{deepseek\_bridge/e32\_event\_measure\_stabilization.png} "
         r"/ \texttt{e32\_event\_measure\_stabilization.json}.}",
         r"exact ($d_{BL} \equiv 0$) from $m \ge 8$.}", 1),
    ]
    for i, (old, new, cnt) in enumerate(S3):
        src, ok = apply(src, old, new, cnt, f"S3-{i}")
        ok_all &= ok

    # ============ STAGE 4: discussion, methods, backmatter ============
    S4 = [
        # Discussion open-items paragraph
        (r"Open items, demoted to their honest status: "
         r"Conjecture~\ref{conj:bridge} (general complex stability) and E28 "
         r"(second differences on measured time courses, under the "
         r"$(\varepsilon, \sigma)$ design law). E32 (event-measure "
         r"stabilization) is now executed (E-E32): the statistical form "
         r"passes --- random panels are Glivenko--Cantelli objects, "
         r"designed panels reproduce the event measure exactly --- and the "
         r"deterministic refinement-sequence form (Route 5 proper) remains "
         r"open.",
         r"Open items: Conjecture~\ref{conj:bridge} (general complex "
         r"stability) and second differences on measured time courses "
         r"(under the $(\varepsilon, \sigma)$ design law). The statistical "
         r"form of the stabilization question is settled here "
         r"(\S\ref{sec:e32}): random panels are Glivenko--Cantelli objects "
         r"and designed panels reproduce the event measure exactly; the "
         r"deterministic refinement-sequence form (refinement along "
         r"explicit model-family sequences) remains open.", 1),
        (r"which supersedes the earlier metric-invariance argument for why "
         r"the association stands on the flux layer.",
         r"which grounds the association's flux-layer footing exactly, "
         r"complementing the measured metric invariance of "
         r"\S\ref{sec:v5}.", 1),
        # Limitations paragraph
        (r"stable across four alternative selection rules, E-V8); the",
         r"stable across four alternative selection rules, \S\ref{sec:v8}); "
         r"the", 1),
        (r"one-chamber structure of the E24 path is condition-specific "
         r"(E-V7) while the layer decision itself is path-robust; the "
         r"cross-platform carbon-switch dissociation (PRECISE, E-V5) "
         r"bounds the generality of the association; the E22 "
         r"active-reaction census (438/2{,}583 and the GPR class counts) "
         r"is plain-FBA and solver-version-sensitive at the "
         r"$\pm 1$-reaction level, while the gene-level panel (435) is "
         r"stable (numeric audit, Appendix~\ref{sec:counts}); the E32 "
         r"sweep arm is panel-limited (thirteen M1 families, two of them "
         r"affine --- the finite-population correction is part of the "
         r"reported result) and the E32 two-dimensional arm is "
         r"floor-limited at large panels by the transport-LP atom cap.",
         r"one-chamber structure of the reference path is "
         r"condition-specific (\S\ref{sec:v7}) while the layer decision "
         r"itself is path-robust; the cross-platform carbon-switch "
         r"dissociation (PRECISE arm, \S\ref{sec:v5}) bounds the "
         r"generality of the association; the active-reaction census of "
         r"the reference physiology (438/2{,}583 and the GPR class "
         r"counts) is plain-FBA and solver-version-sensitive at the "
         r"$\pm 1$-reaction level, while the gene-level panel (435) is "
         r"stable (Appendix~\ref{sec:counts}); the sweep arm of the "
         r"stabilization experiment is panel-limited (thirteen sweep "
         r"families, two of them affine --- the finite-population "
         r"correction is part of the reported result) and the "
         r"two-dimensional arm is floor-limited at large panels by the "
         r"transport-LP atom cap.", 1),
        # Methods: engine
        (r"$w \sim U(0.5, 1.5)$ drawn once with seed 20240901 (the "
         r"M-series protocol).",
         r"$w \sim U(0.5, 1.5)$ drawn once with seed 20240901 and fixed "
         r"thereafter.", 1),
        (r"and its robustness is measured in E-V8. The E22 "
         r"active-reaction census is the one plain-FBA computation "
         r"retained (historical protocol of the precursor metric family); "
         r"it is solver-version-sensitive",
         r"and its robustness is measured in \S\ref{sec:v8}. The "
         r"active-reaction census of the reference physiology is the one "
         r"plain-FBA computation retained (kept for comparability with "
         r"the precursor metric $\kk$); it is solver-version-sensitive", 1),
        # Methods: models and data
        (r"\emph{E.~coli} iJO1366 (2{,}583 reactions) \citep{orth2011} "
         r"for the E-series association experiments; iML1515 "
         r"\citep{monk2017} for the M-series computational batteries "
         r"(M1, M3, M4) and the V1/Theorem-C verification cut.",
         r"\emph{E.~coli} iJO1366 (2{,}583 reactions) \citep{orth2011} "
         r"for the association experiments of \S\ref{sec:empirical}; "
         r"iML1515 \citep{monk2017} for the computational batteries of "
         r"\S\ref{sec:computational} and the value--flux coupling "
         r"verification cut.", 1),
        (r"The E24/E25 expression panels come from the M3D",
         r"The expression panels come from the M3D", 1),
        (r"PRECISE has no carbon-depletion class; the dissociation is "
         r"reported as an honest negative with per-condition values "
         r"(E-V5).",
         r"PRECISE has no carbon-depletion class; the dissociation is "
         r"reported as a negative result with per-condition values "
         r"(\S\ref{sec:v5}).", 1),
        (r"carbon-starvation and the quantitative proteomics arms "
         r"(E-E25/E-E26).",
         r"carbon-starvation and the quantitative proteomics arms "
         r"(\S\S\ref{sec:e25}--\ref{sec:e26}).", 1),
        (r"The E22 panel is built by reaction-based sampling: solve the "
         r"lexicographic trajectory on the E22 physiology (glucose",
         r"The gene panel is built by reaction-based sampling: solve the "
         r"lexicographic trajectory on the reference physiology (glucose", 1),
        (r"The E24 panel is the $433$ genes of this set",
         r"The expression panel consists of the $433$ genes of this set", 1),
        (r"are disambiguated once in the counts ledger of "
         r"Appendix~\ref{sec:counts}.",
         r"are disambiguated in Appendix~\ref{sec:counts}.", 1),
        # Methods: statistical protocols tail
        (r"Numbers in the manuscript trace to committed artifacts via the "
         r"numeric audit (\texttt{scripts/audit\_v2\_numbers.py} $\to$ "
         r"\texttt{download/deepseek\_bridge/v2\_number\_audit.json}; "
         r"$98$ checks).",
         r"Every manuscript number traces to a deposited artifact file "
         r"and is re-derived by the automated numeric verification "
         r"described under Reproducibility ($98$ checks).", 1),
    ]
    for i, (old, new, cnt) in enumerate(S4):
        src, ok = apply(src, old, new, cnt, f"S4-{i}")
        ok_all &= ok

    # Reproducibility subsection rewrite (regex span)
    src, ok = regex(
        src,
        r"All experiments deposit artifacts \(npz/csv/json/png\) with\n"
        r"generating scripts.*?is re-runnable end-to-end\.\n",
        "All experiments deposit their result files and generating\n"
        "scripts in the public repository cited in the Data Availability\n"
        "statement. Independent-seed reproductions are recorded for the\n"
        "refinement prototype and the stress batteries. The "
        "layer-decision,\npath-robustness, and tie-break-robustness "
        "analyses, the cross-platform\narm, and the event-measure "
        "stabilization re-run in minutes each on a\nsingle workstation. "
        "An automated numeric verification re-derives every\nmanuscript "
        "number from the deposited artifacts ($98$ checks) and is\n"
        "re-runnable end-to-end.\n",
        1, "S4-repro", re.S)
    ok_all &= ok

    # Counts appendix header
    src, ok = apply(src,
        r"Near-colliding counts of the manuscript, each traced to a "
        r"single committed artifact (numeric audit, 2026-09-02):",
        r"Near-colliding counts in the manuscript, each traceable to a "
        r"single deposited artifact file (Data Availability):", 1, "S4-counts")
    ok_all &= ok

    # Counts table source column
    S4B = [
        (r"iJO1366 reactions (model file; recomputed E22-2R)",
         r"iJO1366 reactions (model file; recomputed)", 1),
        (r"reactions active on the E22 physiology, $17.0\%$ (v15 "
         r"script printout; plain-FBA, $\pm 1$ solver sensitivity)",
         r"reactions active on the reference physiology, $17.0\%$ "
         r"(plain-FBA census, $\pm 1$ solver sensitivity)", 1),
        (r"reactions with $D_2 > 10^{-8}$ along the E24 trajectory "
         r"(reaction-level event count; V5/V8 json \texttt{n\_events\_rxns})",
         r"reactions with $D_2 > 10^{-8}$ along the reference trajectory "
         r"(reaction-level event count, deposited event file)", 1),
        (r"panel genes with M3D response (E24 csv row count)",
         r"panel genes with M3D response (panel file row count)", 1),
        (r"panel genes with nonzero $\kmu$ --- the $n$ of the primary "
         r"correlation (v5/v6/v8 json \texttt{n\_nonzero})",
         r"panel genes with nonzero $\kmu$ --- the $n$ of the primary "
         r"correlation (deposited metric file)", 1),
        (r"nonzero genes on the P1/P2 paths (V7 json)",
         r"nonzero genes on the P1/P2 paths (deposited path file)", 1),
        (r"genes with $\ge 1$ active reaction, E22 (e22 csv; "
         r"recomputed exactly)",
         r"genes with $\ge 1$ active reaction, reference physiology "
         r"(census file; recomputed exactly)", 1),
        (r"max active reactions across the nine E23 conditions (v16 "
         r"results json)",
         r"max active reactions across the nine multi-condition panels "
         r"(deposited multi-condition results)", 1),
        (r"union of active reactions across conditions, $20.8\%$ (v16 "
         r"results json)",
         r"union of active reactions across conditions, $20.8\%$ "
         r"(deposited multi-condition results)", 1),
        (r"genes with nonzero $\kappa$ across conditions (v16 results "
         r"json)",
         r"genes with nonzero $\kappa$ across conditions (deposited "
         r"multi-condition results)", 1),
        (r"trajectory atoms of the E24 event measure --- the four design "
         r"corners carrying the full flux-layer mass $288.77$; identical "
         r"to the value-kink positions (V6/E32 jsons)",
         r"trajectory atoms of the event measure --- the four design "
         r"corners carrying the full flux-layer mass $288.77$; identical "
         r"to the value-kink positions (deposited event files)", 1),
        (r"M4b boundary edges of the $(q_{\mathrm{glc}}, q_{O_2})$ "
         r"signature census, full $34\times34$ grid (m4b grid npz)",
         r"boundary edges of the $(q_{\mathrm{glc}}, q_{O_2})$ signature "
         r"census, full $34\times34$ grid (deposited census grid)", 1),
        (r"cut events in the E32 random-cut pool, $4{,}000$ cuts "
         r"(e32 json)",
         r"cut events in the random-cut pool, $4{,}000$ cuts (deposited "
         r"stabilization file)", 1),
        (r"iML1515 genes, M3 single knockouts (m3 json)",
         r"iML1515 genes, single knockouts (deposited knockout file)", 1),
        (r"double-knockout pairs, five panels (m3 json)",
         r"double-knockout pairs, five panels (deposited knockout file)", 1),
    ]
    for i, (old, new, cnt) in enumerate(S4B):
        src, ok = apply(src, old, new, cnt, f"S4B-{i}")
        ok_all &= ok

    # Proofs appendix: code refs
    src, ok = apply(src,
        r"segment residuals $\le 8 \times 10^{-14}$ (E-M1 glucose) and "
        r"$\Phi$ piecewise affine at $4.2 \times 10^{-13}$ (E-V1).",
        r"segment residuals $\le 8 \times 10^{-14}$ (\S\ref{sec:m1}, "
        r"glucose sweep) and $\Phi$ piecewise affine at $4.2 \times "
        r"10^{-13}$ (\S\ref{sec:v1}).", 1, "S4-proof")
    ok_all &= ok
    src, ok = apply(src,
        r"Theorem~\ref{thm:coupling} is the exact form of the "
        r"value--flux relation previously left open: the",
        r"Theorem~\ref{thm:coupling} is the exact form of the "
        r"value--flux layer relation: the", 1, "S4-closes")
    ok_all &= ok

    # Provenance note removal
    src, ok = regex(
        src,
        r"\\noindent\\emph\{Provenance note \(for editors and reviewers\)"
        r"\..*?\n\n(?=\\section\*)",
        "", 1, "S4-provnote", re.S)
    ok_all &= ok

    # Layer-1 port comments removal
    src, ok = regex(src, r"\n% \[Layer-1 port[^\n]*(?:\n% [^\n]*)*",
                    "\n", 5, "S4-comments")
    ok_all &= ok

    # ============ STAGE 5: companion paper ============
    comp = open(COMP, encoding="utf-8").read()
    S5 = [
        (r"Two results of the predecessor lineage that were superseded "
         r"rather than repaired --- the smooth-surrogate envelope line "
         r"and the indicator-weighted operational curvature --- are "
         r"\emph{not} carried here: the first is superseded in the "
         r"application paper by the measure-theoretic development, the "
         r"second by its locked metric. Open",
         r"Open", 1),
        (r"This preserves the $\CO(r)$ ambition in a mathematically "
         r"honest way: $\CO(r)$ is an",
         r"This preserves the $\CO(r)$ ambition with mathematical "
         r"precision: $\CO(r)$ is an", 1),
        (r"falsifiable. The audit's core distinction is between",
         r"falsifiable. The closure test's core distinction is between", 1),
        (r"A predecessor of this framework also carried an "
         r"\emph{FBA-operational} viability-weighted curvature: an "
         r"indicator-masked, gene-knockout flux-rerouting statistic "
         r"whose indicator imports the model's own essentiality call "
         r"into the predictor, and whose adoption was justified post hoc "
         r"by the strengthening it produced in two empirical studies. "
         r"That object is \emph{not} carried in this paper: it is "
         r"superseded, in the application paper \citep{zai2026measure}, "
         r"by a measure-theoretic sensitivity metric derived from the "
         r"atomic curvature measure of parametric FBA --- a "
         r"construction whose selection-rule dependence is exposed and "
         r"audited rather than masked (tie-break robustness across five "
         r"lexicographic selection rules), and whose empirical "
         r"validation carries an explicit protein-layer null.",
         r"An operational curvature is deliberately \emph{not} defined "
         r"here. A tempting construction --- an indicator-masked, "
         r"gene-knockout flux-rerouting statistic --- imports the "
         r"model's own essentiality call into the predictor and is "
         r"circular as a result. The application paper "
         r"\citep{zai2026measure} instead derives a measure-theoretic "
         r"sensitivity metric from the atomic curvature measure of "
         r"parametric FBA, one whose selection-rule dependence is "
         r"exposed and stress-tested rather than masked (tie-break "
         r"robustness across five lexicographic selection rules) and "
         r"whose empirical validation carries an explicit protein-layer "
         r"null.", 1),
        (r"The following problems are open. Items previously listed as "
         r"future directions in the predecessor lineage and since "
         r"resolved (the $2$-categorical gluing, the piecewise-holonomy "
         r"verification across loop geometries and structure groups, "
         r"the filtered-colimit construction and its scale-up, the "
         r"contraction agenda, the $\infty$-categorical extension at "
         r"sketch level) are closed in the body of this paper and are "
         r"not repeated here.",
         r"The following problems are open.", 1),
        (r"each should carry the selection-rule robustness audit that "
         r"the application paper introduces.",
         r"each should carry the selection-rule robustness check that "
         r"the application paper introduces.", 1),
    ]
    for i, (old, new, cnt) in enumerate(S5):
        comp, ok = apply(comp, old, new, cnt, f"S5-{i}")
        ok_all &= ok
    with open(COMP, "w", encoding="utf-8") as f:
        f.write(comp)

    print("\n".join(REPORT))
    with open(MAIN, "w", encoding="utf-8") as f:
        f.write(src)
    print(f"\nALL STAGES {'COMPLETE' if ok_all else 'HAD MISSES'}: "
          f"{MAIN} + {COMP}")
    return 0 if ok_all else 1


if __name__ == "__main__":
    sys.exit(main())
